Physikz: Shape Class Reference
Shape Class Reference abstract
#include <Shape.h>
Public Member Functions
virtual void Draw (NVGcontext *ctx, std::shared_ptr< Entity > entity) const =0
virtual Manifold IsColliding (std::shared_ptr< Entity > entityA, std::shared_ptr< Entity > entityB, const Shape *shapeB) const =0
virtual Manifold IsColliding (std::shared_ptr< Entity > entityA, std::shared_ptr< Entity > entityB, const Circle *shapeB) const =0
virtual Manifold IsColliding (std::shared_ptr< Entity > entityA, std::shared_ptr< Entity > entityB, const Rectangle *shapeB) const =0
virtual Manifold IsColliding (std::shared_ptr< Entity > entityA, std::shared_ptr< Entity > entityB, const Line *shapeB) const =0
Data Fields
NVGcolor color = nvgRGB(255, 0, 0)
Detailed Description
Definition at line 12 of file Shape.h.
Member Function Documentation
Draw()
virtual void Shape::Draw (NVGcontext * ctx, std::shared_ptr< Entity > entity) const pure virtual
Implemented in Line, Circle, and Rectangle.
IsColliding() [1/4]
virtual Manifold Shape::IsColliding (std::shared_ptr< Entity > entityA, std::shared_ptr< Entity > entityB, const Circle * shapeB) const pure virtual
Implemented in Line, Circle, and Rectangle.
IsColliding() [2/4]
virtual Manifold Shape::IsColliding (std::shared_ptr< Entity > entityA, std::shared_ptr< Entity > entityB, const Line * shapeB) const pure virtual
Implemented in Line, Circle, and Rectangle.
IsColliding() [3/4]
virtual Manifold Shape::IsColliding (std::shared_ptr< Entity > entityA, std::shared_ptr< Entity > entityB, const Rectangle * shapeB) const pure virtual
Implemented in Line, Circle, and Rectangle.
IsColliding() [4/4]
virtual Manifold Shape::IsColliding (std::shared_ptr< Entity > entityA, std::shared_ptr< Entity > entityB, const Shape * shapeB) const pure virtual
Implemented in Line, Circle, and Rectangle.
Referenced by Rectangle::IsColliding(), Circle::IsColliding(), and Line::IsColliding().
Field Documentation
color
NVGcolor Shape::color = nvgRGB(255, 0, 0)
Definition at line 15 of file Shape.h.
Referenced by Rectangle::Draw(), Circle::Draw(), and Line::Draw().
The documentation for this class was generated from the following file:
include/Collision/Shape.h