Physikz: Circle Class Reference
Circle Class Reference
#include <Circle.h>
Public Member Functions
Circle (float _radius)
void Draw (NVGcontext *ctx, std::shared_ptr< Entity > entity) const override
Manifold IsColliding (std::shared_ptr< Entity > entityA, std::shared_ptr< Entity > entityB, const Shape *shapeB) const override
Manifold IsColliding (std::shared_ptr< Entity > entityA, std::shared_ptr< Entity > entityB, const Circle *shapeB) const override
Manifold IsColliding (std::shared_ptr< Entity > entityA, std::shared_ptr< Entity > entityB, const Rectangle *shapeB) const override
Manifold IsColliding (std::shared_ptr< Entity > entityA, std::shared_ptr< Entity > entityB, const Line *shapeB) const override
Data Fields
float radius
Data Fields inherited from Shape
NVGcolor color = nvgRGB(255, 0, 0)
Detailed Description
Definition at line 8 of file Circle.h.
Constructor & Destructor Documentation
Circle()
Circle::Circle (float _radius)
Definition at line 6 of file Circle.cpp.
 {
     radius = _radius;
 }
References radius.
Member Function Documentation
Draw()
void Circle::Draw (NVGcontext * ctx, std::shared_ptr< Entity > entity) const override virtual
Implements Shape.
Definition at line 11 of file Circle.cpp.
 {
     nvgBeginPath(ctx);
     nvgCircle(ctx, entity->position.x, entity->position.y, radius);
     nvgFillColor(ctx, color);
     nvgFill(ctx);
     nvgBeginPath(ctx);
     nvgMoveTo(ctx, entity->position.x, entity->position.y);
     nvgLineTo(ctx, entity->position.x + sin(entity->rotation) * radius, entity->position.y + cos(entity->rotation) * radius);
     nvgStrokeColor(ctx, nvgRGB(0,0,255));
     nvgStroke(ctx);
 }
References Shape::color, Entity::position, radius, Entity::rotation, Vec2d::x, and Vec2d::y.
IsColliding() [1/4]
Manifold Circle::IsColliding (std::shared_ptr< Entity > entityA, std::shared_ptr< Entity > entityB, const Circle * shapeB) const override virtual
Implements Shape.
Definition at line 30 of file Circle.cpp.
 {
     return Util::CreateManifoldCircleVsCircle(entityA, this, entityB, shapeB);
 }
References Util::CreateManifoldCircleVsCircle().
IsColliding() [2/4]
Manifold Circle::IsColliding (std::shared_ptr< Entity > entityA, std::shared_ptr< Entity > entityB, const Line * shapeB) const override virtual
Implements Shape.
Definition at line 43 of file Circle.cpp.
 {
     return Util::CreateManifoldCircleVsLine(entityA, this, entityB, shapeB);
 }
References Util::CreateManifoldCircleVsLine().
IsColliding() [3/4]
Manifold Circle::IsColliding (std::shared_ptr< Entity > entityA, std::shared_ptr< Entity > entityB, const Rectangle * shapeB) const override virtual
Implements Shape.
Definition at line 35 of file Circle.cpp.
 {
     // std::cout << "Circle vs Rect" << std::endl;
     Manifold manifold = Manifold();
     manifold.isColliding = false;
     return manifold;
 }
References Manifold::isColliding.
IsColliding() [4/4]
Manifold Circle::IsColliding (std::shared_ptr< Entity > entityA, std::shared_ptr< Entity > entityB, const Shape * shapeB) const override virtual
Implements Shape.
Definition at line 25 of file Circle.cpp.
 {
     return shapeB->IsColliding(entityB, entityA, this);
 }
References Shape::IsColliding().
Field Documentation
radius
float Circle::radius
Definition at line 11 of file Circle.h.
Referenced by Circle(), Util::CreateManifoldCircleVsCircle(), Util::CreateManifoldCircleVsLine(), and Draw().
The documentation for this class was generated from the following files:
include/Collision/Circle.h
src/Collision/Circle.cpp