Physikz: Entity Class Reference
Entity Class Reference
#include <Entity.h>
Public Member Functions
Entity (Vec2d _pos, std::shared_ptr< Shape > _shape)
Manifold IsColliding (std::shared_ptr< Entity > other)
Data Fields
Vec2d position = Vec2d(0, 0)
Vec2d velocity = Vec2d(0, 0)
Vec2d force = Vec2d(0, 0)
float rotation = 1
float mass = 1
float restitution = 1
float staticFriction = 0.1
float dynamicFriction = 0.1
std::shared_ptr< Shape > shape
SimType type = SimType::Dynamic
Detailed Description
Definition at line 9 of file Entity.h.
Constructor & Destructor Documentation
Entity()
Entity::Entity (Vec2d _pos, std::shared_ptr< Shape > _shape)
Definition at line 3 of file Entity.cpp.
 {
     position = _pos;
     shape = _shape;
 }
References position, and shape.
Member Function Documentation
IsColliding()
Manifold Entity::IsColliding (std::shared_ptr< Entity > other)
Definition at line 9 of file Entity.cpp.
 {
     return shape->IsColliding(shared_from_this(), other, other->shape.get());
 }
References shape.
Field Documentation
dynamicFriction
float Entity::dynamicFriction = 0.1
Definition at line 26 of file Entity.h.
force
Vec2d Entity::force = Vec2d(0, 0)
Definition at line 17 of file Entity.h.
mass
float Entity::mass = 1
Definition at line 23 of file Entity.h.
position
Vec2d Entity::position = Vec2d(0, 0)
Definition at line 15 of file Entity.h.
Referenced by Util::CreateManifoldCircleVsCircle(), Util::CreateManifoldCircleVsLine(), Rectangle::Draw(), Circle::Draw(), and Entity().
restitution
float Entity::restitution = 1
Definition at line 24 of file Entity.h.
rotation
float Entity::rotation = 1
Definition at line 20 of file Entity.h.
Referenced by Circle::Draw().
shape
std::shared_ptr<Shape> Entity::shape
Definition at line 27 of file Entity.h.
Referenced by Entity(), and IsColliding().
staticFriction
float Entity::staticFriction = 0.1
Definition at line 25 of file Entity.h.
type
SimType Entity::type = SimType::Dynamic
Definition at line 28 of file Entity.h.
velocity
Vec2d Entity::velocity = Vec2d(0, 0)
Definition at line 16 of file Entity.h.
The documentation for this class was generated from the following files:
include/Entity.h
src/Entity.cpp