Physikz: Vec2d Class Reference
Vec2d Class Reference
#include <Vec2d.h>
Public Member Functions
Vec2d ()
Vec2d (float _x, float _y)
float Length () const
Vec2d Normalized () const
Vec2d Orthogonal () const
Vec2d operator* (float a) const
Vec2d operator/ (float a) const
Vec2d & operator+= (const Vec2d &a)
Vec2d & operator-= (const Vec2d &a)
Vec2d operator+ (const Vec2d &a) const
Vec2d operator- (const Vec2d &a) const
Static Public Member Functions
static float Dot (const Vec2d &a, const Vec2d &b)
Data Fields
float x
float y
Detailed Description
Definition at line 5 of file Vec2d.h.
Constructor & Destructor Documentation
Vec2d() [1/2]
Vec2d::Vec2d ()
Definition at line 3 of file Vec2d.cpp.
 {
     x = 0;
     y = 0;
 }
References x, and y.
Referenced by Normalized(), operator*(), operator+(), operator-(), operator/(), and Orthogonal().
Vec2d() [2/2]
Vec2d::Vec2d (float _x, float _y)
Definition at line 9 of file Vec2d.cpp.
 {
     x = _x;
     y = _y;
 }
References x, and y.
Member Function Documentation
Dot()
float Vec2d::Dot (const Vec2d & a, const Vec2d & b) static
Definition at line 67 of file Vec2d.cpp.
 {
     return a.x * b.x + a.y * b.y;
 }
References x, and y.
Referenced by Util::CreateManifoldCircleVsLine(), and Util::ResolveImpulse().
Length()
float Vec2d::Length () const
Definition at line 15 of file Vec2d.cpp.
 {
     return sqrt(x*x+y*y);
 }
References x, and y.
Referenced by Util::CreateManifoldCircleVsCircle(), and Normalized().
Normalized()
Vec2d Vec2d::Normalized () const
Definition at line 20 of file Vec2d.cpp.
 {
     if(Length() == 0)
         return Vec2d();
     return *this / Length();
 }
References Length(), and Vec2d().
Referenced by Util::CreateManifoldCircleVsLine().
operator*()
Vec2d Vec2d::operator* (float a) const
Definition at line 33 of file Vec2d.cpp.
 {
     return Vec2d(x*a, y*a);
 }
References Vec2d(), x, and y.
operator+()
Vec2d Vec2d::operator+ (const Vec2d & a) const
Definition at line 57 of file Vec2d.cpp.
 {
     return Vec2d(x + a.x, y + a.y);
 }
References Vec2d(), x, and y.
operator+=()
Vec2d & Vec2d::operator+= (const Vec2d & a)
Definition at line 43 of file Vec2d.cpp.
 {
     x += a.x;
     y += a.y;
     return *this;
 }
References x, and y.
operator-()
Vec2d Vec2d::operator- (const Vec2d & a) const
Definition at line 62 of file Vec2d.cpp.
 {
     return Vec2d(x - a.x, y - a.y);
 }
References Vec2d(), x, and y.
operator-=()
Vec2d & Vec2d::operator-= (const Vec2d & a)
Definition at line 50 of file Vec2d.cpp.
 {
     x -= a.x;
     y -= a.y;
     return *this;
 }
References x, and y.
operator/()
Vec2d Vec2d::operator/ (float a) const
Definition at line 38 of file Vec2d.cpp.
 {
     return Vec2d(x/a, y/a);
 }
References Vec2d(), x, and y.
Orthogonal()
Vec2d Vec2d::Orthogonal () const
Definition at line 28 of file Vec2d.cpp.
 {
     return Vec2d(-y, x);
 }
References Vec2d(), x, and y.
Field Documentation
x
float Vec2d::x
Definition at line 11 of file Vec2d.h.
Referenced by Util::CreateManifoldCircleVsLine(), Dot(), Rectangle::Draw(), Circle::Draw(), Length(), operator*(), operator+(), operator+=(), operator-(), operator-=(), operator/(), Orthogonal(), and Vec2d().
y
float Vec2d::y
Definition at line 11 of file Vec2d.h.
Referenced by Util::CreateManifoldCircleVsLine(), Dot(), Rectangle::Draw(), Circle::Draw(), Length(), operator*(), operator+(), operator+=(), operator-(), operator-=(), operator/(), Orthogonal(), and Vec2d().
The documentation for this class was generated from the following files:
include/Vec2d.h
src/Vec2d.cpp