Physikz: Scene Class Reference
Scene Class Reference
#include <Scene.h>
Public Member Functions
Scene ()
Scene (std::vector< std::shared_ptr< Entity >> _entities)
void Add (std::shared_ptr< Entity > entity)
void Step (float dT)
std::vector< std::shared_ptr< Entity > > getEntities () const
Private Attributes
std::vector< std::shared_ptr< Entity > > entities = {}
Vec2d gravity_coeff = Vec2d(0, 9.82*6)
Detailed Description
Definition at line 8 of file Scene.h.
Constructor & Destructor Documentation
Scene() [1/2]
Scene::Scene ()
Definition at line 3 of file Scene.cpp.
 {
 }
Scene() [2/2]
Scene::Scene (std::vector< std::shared_ptr< Entity >> _entities)
Definition at line 8 of file Scene.cpp.
 {
     entities = _entities;
 }
References entities.
Member Function Documentation
Add()
void Scene::Add (std::shared_ptr< Entity > entity)
Definition at line 13 of file Scene.cpp.
 {
     entities.push_back(entity);
 }
References entities.
Referenced by App::App().
getEntities()
std::vector< std::shared_ptr< Entity > > Scene::getEntities () const
Definition at line 18 of file Scene.cpp.
 {
     return entities;
 }
References entities.
Step()
void Scene::Step (float dT)
Definition at line 23 of file Scene.cpp.
 {
     for(auto& entity : entities) {
         std::vector<Manifold> collisions = {};
         // Check collisions
         for(auto& other : entities) {
             if(entity == other) continue;
             auto manifold = entity->IsColliding(other);
             if(manifold.isColliding) {
                 entity->shape.get()->color = nvgRGBA(0, 255, 0, 122);
                 collisions.push_back(manifold);
             }
         }
         if(entity->type == SimType::Dynamic) {
             // Resolve gravity
             entity->force += gravity_coeff * entity->mass;
             entity->velocity += entity->force / entity->mass * dT;
             // Resolve collisions with impulse
             for(auto& collision : collisions)
                 Util::ResolveImpulse(collision);
             // Resolve velocity
             entity->position += entity->velocity * dT;
             // Resolve collisions with position correction
             for(auto& collision : collisions)
                 Util::ResolvePosition(collision);
             // Clear forces
             entity->force = Vec2d();
         }
     }
 }
References Dynamic, entities, gravity_coeff, Util::ResolveImpulse(), and Util::ResolvePosition().
Field Documentation
entities
std::vector<std::shared_ptr<Entity> > Scene::entities = {} private
Definition at line 18 of file Scene.h.
Referenced by Add(), getEntities(), Scene(), and Step().
gravity_coeff
Vec2d Scene::gravity_coeff = Vec2d(0, 9.82*6) private
Definition at line 19 of file Scene.h.
Referenced by Step().
The documentation for this class was generated from the following files:
include/Scene.h
src/Scene.cpp