Physikz: Util Namespace Reference
Util Namespace Reference
Functions
Manifold CreateManifoldCircleVsCircle (std::shared_ptr< Entity > entityA, const Circle *circleA, std::shared_ptr< Entity > entityB, const Circle *circleB)
Manifold CreateManifoldCircleVsLine (std::shared_ptr< Entity > entityA, const Circle *circleA, std::shared_ptr< Entity > entityB, const Line *lineB)
void ResolveImpulse (Manifold &manifold)
void ResolvePosition (Manifold &manifold)
auto tolower (std::string str) -> std::string
template<class T >
auto vectorContainsElement (const T &elem, const std::vector< T > &list) -> bool
auto getBackendName (bgfx::RendererType::Enum backend) -> std::string
auto getBackendFromName (std::string backendName) -> bgfx::RendererType::Enum
auto getValidBackends () -> std::vector< bgfx::RendererType::Enum >
auto getFileData (const cmrc::file &file) -> uint8_t *
float RadToDeg (float rad)
Variables
const std::unordered_map< bgfx::RendererType::Enum, std::string > backend_names
Function Documentation
CreateManifoldCircleVsCircle()
Manifold Util::CreateManifoldCircleVsCircle (std::shared_ptr< Entity > entityA, const Circle * circleA, std::shared_ptr< Entity > entityB, const Circle * circleB)
Definition at line 6 of file CollisionHelper.cpp.
 {
     Manifold manifold = Manifold();
     // The incident normal must be the vector between the positions of the circles
     manifold.normal = entityA->position - entityB->position;
     // If the length of the "normal" is greater than the combined radius, then there is no collision
     float distance = manifold.normal.Length();
     float radius = circleA->radius + circleB->radius;
     if(distance >= radius) {
         manifold.isColliding = false;
         return manifold;
     }
     manifold.isColliding = true;
     manifold.depth = radius - distance;
     manifold.normal = manifold.normal / distance; // Creates a normalized vector or "enhedsvektor"
     manifold.collisionPoint = entityA->position + manifold.normal*circleA->radius;
     manifold.entityA = entityA;
     manifold.entityB = entityB;
     return manifold;
 }
References Manifold::collisionPoint, Manifold::depth, Manifold::entityA, Manifold::entityB, Manifold::isColliding, Vec2d::Length(), Manifold::normal, Entity::position, and Circle::radius.
Referenced by Circle::IsColliding().
CreateManifoldCircleVsLine()
Manifold Util::CreateManifoldCircleVsLine (std::shared_ptr< Entity > entityA, const Circle * circleA, std::shared_ptr< Entity > entityB, const Line * lineB)
Definition at line 29 of file CollisionHelper.cpp.
 {
     Manifold manifold = Manifold();
     // Create normal vector
     const Vec2d dir = Vec2d(0, lineB->b) - Vec2d(1, lineB->a + lineB->b);
     manifold.normal = Vec2d(-dir.y, dir.x).Normalized() * -1;
     // Create vector between circle and line and project on normal vector to find distance
     const Vec2d circToLine = entityA->position - Vec2d(0, lineB->b);
     float distance = Vec2d::Dot(manifold.normal, circToLine);
     if(distance + circleA->radius >= 0) {
         // We have a collision
         manifold.isColliding = true;
         manifold.depth = distance + circleA->radius;
         manifold.collisionPoint = entityA->position - manifold.normal * manifold.depth;
         manifold.entityA = entityB;
         manifold.entityB = entityA;
     } else {
         manifold.isColliding = false;
     }
     return manifold;
 }
References Line::a, Line::b, Manifold::collisionPoint, Manifold::depth, Vec2d::Dot(), Manifold::entityA, Manifold::entityB, Manifold::isColliding, Manifold::normal, Vec2d::Normalized(), Entity::position, Circle::radius, Vec2d::x, and Vec2d::y.
Referenced by Circle::IsColliding(), and Line::IsColliding().
getBackendFromName()
auto Util::getBackendFromName (std::string backendName) -> bgfx::RendererType::Enum
Definition at line 14 of file Util.cpp.
 {
     for(auto item : backend_names) {
         if(item.second == backendName)
             return item.first;
     }
     // We have not found any backend for this name, throw an error
     throw std::runtime_error("ERROR: Could not find a valid backend for \"" + backendName + "\"");
 }
References backend_names.
Referenced by main().
getBackendName()
auto Util::getBackendName (bgfx::RendererType::Enum backend) -> std::string
Definition at line 8 of file Util.cpp.
 {
     // Since every enum is in the map, this should not be able to fail
     return backend_names.at(backend);
 }
References backend_names.
Referenced by main().
getFileData()
auto Util::getFileData (const cmrc::file & file) -> uint8_t*
Definition at line 39 of file Util.cpp.
 {
     return (uint8_t*)std::string_view(file.begin(), file.end() - file.begin()).data();
 }
Referenced by App::App().
getValidBackends()
auto Util::getValidBackends () -> std::vector<bgfx::RendererType::Enum>
Definition at line 25 of file Util.cpp.
 {
     bgfx::RendererType::Enum rendererTypes[bgfx::RendererType::Count];
     auto numberOfBackends = bgfx::getSupportedRenderers(bgfx::RendererType::Count, rendererTypes);
     auto backendList = std::vector<bgfx::RendererType::Enum>();
     for(auto i = 0; i < numberOfBackends; i++) {
         backendList.push_back(rendererTypes[i]);
     }
     return backendList;
 }
Referenced by main().
RadToDeg()
float Util::RadToDeg (float rad)
Definition at line 44 of file Util.cpp.
 {
     return rad * 180.f / 3.1415926536f;
 }
ResolveImpulse()
void Util::ResolveImpulse (Manifold & manifold)
Definition at line 6 of file Resolver.cpp.
 {
     // Formulas can be found here: http://www.chrishecker.com/images/e/e7/Gdmphys3.pdf
     const bool staticA = m.entityA->type == SimType::Static;
     const bool staticB = m.entityB->type == SimType::Static;
     if(staticA && staticB) // Both entities are static, no need for collision resolution
         return;
     // We zero out velocity if static
     if(staticA) {
         m.entityA->velocity = Vec2d();
     }
     if(staticB) {
         m.entityB->velocity = Vec2d();
     }
     // Calculate radius from contactpoint to center
     Vec2d radiusA = m.collisionPoint - m.entityA->position;
     Vec2d radiusB = m.collisionPoint - m.entityB->position;
     // Equation 7 from the linked pdf
     Vec2d relativeVelocity = m.entityB->velocity - m.entityA->velocity;
     // We can find the speed of the entities relative to the contact point by
     // projecting the relative velocity onto the normal vector.
     // Since the normal vector is normalized, we just use the dot product
     // (see: https://www.webmatematik.dk/lektioner/sarligt-for-htx/vektorer-i-planen/projektion-fra-enhedsvektor)
     // Also eq. 2 from pdf
     float contactSpeed = Vec2d::Dot(relativeVelocity, m.normal);
     // Negative velocity means the entities are moving away from each other
     // In that case there is no need for collision resolution
     if(contactSpeed < 0)
         return;
     // Calculate a combined restitution or bounciness
     float e = m.entityA->restitution*m.entityB->restitution;
     // Create an impulse scalar (eq. 6 from pdf)
     // NOTE: The formula has been changed from eq. 6 to use contact speed instead of relative velocity
     // This makes it a litte simpler, but we have to use a square root for normalization, which inhibits performance
     float j = -(1+e)*contactSpeed/(1/m.entityA->mass + 1/m.entityB->mass);
     // Eq. 8.a to calculate speed change from impulse
     Vec2d impulseA = (m.normal * j)/m.entityA->mass;
     Vec2d impulseB = (m.normal * j)/m.entityB->mass;
     // From newtons third law, an action has an opposite reaction, therefore
     // when we add velocity to one object we remove from another
     m.entityA->velocity -= impulseA;
     m.entityB->velocity += impulseB;
     // Calculate friction
     // Since we have updated the velocoties, we need to redo the earlier calculations
     if(staticA) {
         m.entityA->velocity = Vec2d();
     }
     if(staticB) {
         m.entityB->velocity = Vec2d();
     }
     relativeVelocity = m.entityB->velocity - m.entityA->velocity;
     contactSpeed = Vec2d::Dot(relativeVelocity, m.normal);
     // We create a tangent vector to the incident face, which descripes the friction force direction
     Vec2d tangent = (relativeVelocity - m.normal * contactSpeed ).Normalized();
     // By projection the relative velocity onto the tangent we get the "sliding" speed or friction speed
     float frictionSpeed = Vec2d::Dot(relativeVelocity, tangent);
     float staticFriction = sqrt(m.entityA->staticFriction * m.entityB->staticFriction);
     float dynamicFriction = sqrt(m.entityA->dynamicFriction * m.entityB->dynamicFriction);
     // Calculate scalar for friction impulse
     float fj = -frictionSpeed / (1/m.entityA->mass + 1/m.entityB->mass);
     if(abs(fj) < 0.001)
         return;
     Vec2d friction;
     if(abs(fj) < j * staticFriction)
         friction = tangent * fj; // If the friction is small, then static friciton applies
     else
         friction = tangent * -j * dynamicFriction; // otherwise dynamic friciton
     // Apply friction impulses
     if(!staticA) {
         m.entityA->velocity += friction/m.entityA->mass;
     }
     if(!staticB) {
         m.entityB->velocity -= friction/m.entityB->mass;
     }
 }
References Manifold::collisionPoint, Vec2d::Dot(), Manifold::entityA, Manifold::entityB, Manifold::normal, and Static.
Referenced by Scene::Step().
ResolvePosition()
void Util::ResolvePosition (Manifold & manifold)
Definition at line 101 of file Resolver.cpp.
 {
     // Position resolution is about reducing the penetration depth a certain percantage
     // to prevent objects from sinking
     float maxDepth= 0.1f;
     float correctionPercentage = 1.f;
     float correctionScalar = (std::max(m.depth - maxDepth, 0.0f)*m.entityA->mass*m.entityB->mass/(m.entityA->mass + m.entityB->mass));
     Vec2d correction = m.normal * correctionScalar * correctionPercentage;
     m.entityA->position += m.entityA->type == SimType::Dynamic? correction / m.entityA->mass : Vec2d();
     m.entityB->position -= m.entityB->type == SimType::Dynamic? correction / m.entityB->mass : Vec2d();
 }
References Manifold::depth, Dynamic, Manifold::entityA, Manifold::entityB, and Manifold::normal.
Referenced by Scene::Step().
tolower()
auto Util::tolower (std::string str) -> std::string
Definition at line 3 of file Util.cpp.
{
     std::transform(str.begin(), str.end(), str.begin(), static_cast<int(*)(int)>(std::tolower));
     return str;
 }
vectorContainsElement()
template<class T > auto Util::vectorContainsElement (const T & elem, const std::vector< T > & list) -> bool
Definition at line 32 of file Util.h.
 {
     return std::find(list.begin(), list.end(), elem) != list.end();
 }
Variable Documentation
backend_names
const std::unordered_map<bgfx::RendererType::Enum, std::string> Util::backend_names
Initial value:
= {
    {bgfx::RendererType::Noop,          "Noop"      },
    {bgfx::RendererType::Count,         "Auto"},
    {bgfx::RendererType::Direct3D9,     "DirectX9"  },
    {bgfx::RendererType::Direct3D11,    "DirectX11" },
    {bgfx::RendererType::Direct3D12,    "DirectX12" },
    {bgfx::RendererType::Gnm,           "Gnm"       },
    {bgfx::RendererType::Nvn,           "Nvn"       },
    {bgfx::RendererType::Metal,         "Metal"     },
    {bgfx::RendererType::Vulkan,        "Vulkan"    },
    {bgfx::RendererType::OpenGL,        "OpenGL"    },
    {bgfx::RendererType::OpenGLES,      "OpenGLES"  },
    {bgfx::RendererType::WebGPU,        "WebGPU"    },
}
Definition at line 13 of file Util.h.
Referenced by getBackendFromName(), and getBackendName().